[tools]
go = "1.25.2"
"gotestsum" = "v1.13.0"
"goreleaser" = "v2.12.5"

[tasks.test]
description = "Run unit + local e2e tests"
run = "gotestsum --hide-summary=skipped -f testname ./... -- -count=1"

[tasks.coverage]
description = "Run all tests with coverage report"
run = """
gotestsum -- -cover -coverprofile=c.out -count=1 -coverpkg=./... ./...
go tool cover -html=c.out
"""
env = { RUN_REMOTE = "0" }

[tasks."test-all"]
description = "Run all tests"
run = "gotestsum -f testname ./... -- -count=1"
env = { RUN_REMOTE = "0" }

[tasks.build]
description = "Build binary"
run = "goreleaser build --snapshot --clean --single-target"

[tasks."build-all"]
description = "Build binary and docker images"
run = "goreleaser release --snapshot --clean --skip=archive"

[tasks."ci-release"]
description = "Build and push release"
run = "goreleaser release --clean"
