name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write # needed to write releases
  packages: write # needed for pushing to ghcr

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Install go with action instead of mise due to the caching it provides
      - name: Set up Go
        uses: actions/setup-go@v6

      - uses: jdx/mise-action@v3
        with:
          version: v2025.10.8
          install: true
          install_args: "gotestsum goreleaser"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: mise test-all

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Run GoReleaser
        run: mise ci-release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
