name: Build and Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v3
        with:
          version: v2025.10.8
          install: true
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v3
        with:
          version: v2025.10.8
          install: true
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise build
