name: Build and Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Install go with action instead of mise due to the caching it provides
      - name: Set up Go
        uses: actions/setup-go@v6

      - uses: jdx/mise-action@v3
        with:
          version: v2025.10.8
          install: true
          install_args: "gotestsum"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: mise test-all

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Install go with action instead of mise due to the caching it provides
      - name: Set up Go
        uses: actions/setup-go@v6

      - uses: jdx/mise-action@v3
        with:
          version: v2025.10.8
          install: true
          install_args: "goreleaser"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with goreleaser
        run: mise build
